### ISSUE TITLE
How to get around the known bug of "failing -locknow" when X is grabbed by others

### ISSUE THREAD

**Issue by bohrshaw** [l0b0/xautolock#1]
There's a talk about this on http://unix.stackexchange.com/questions/241186/why-does-desktop-locking-stop-working-after-some-time

And it can be reproduced by calling `mpv` before calling `xautolock -locknow`.

**Comment by l0b0** [comment]
Hi @BohrShaw,

I posted that. I'm afraid this repository is simply a copy of [what I could find upstream](https://github.com/l0b0/xautolock/commit/93741214ba41b82ad1a6bd56ad5da28cfb4fe87a), since the original repository seems to be unavailable. I'm not working on this project, but I'll leave this open in case anybody decides to fork.

**Comment by bohrshaw** [comment]
Oh! I was blind to not recognize you are the OP.
